# Generated by Django 3.0.3 on 2020-07-29 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20200729_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reserved',
            field=models.ManyToManyField(blank=True, related_name='event_reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
